version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.13"
  apt_packages:
    # core-admin
    - graphviz
    # core-qrexec
    - gobject-introspection
    - libgirepository1.0-dev
  jobs:
    build:
      html:
        - make --keep-going --ignore-errors full-html

submodules:
  include: all
  recursive: true

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

python:
  install:
   - requirements: requirements-full.txt

formats:
- pdf
- epub
- htmlzip
